import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@aws-amplify/ui-react/styles.css'
import { Bootstrap } from './Bootstrap'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <Bootstrap>{children}</Bootstrap>
      </body>
    </html>
  )
}
